version: "2"
services:
  postgres:
    image: registry.centos.org/sclo/postgresql-94-centos7:latest
    environment:
      POSTGRESQL_USER: anitya
      POSTGRESQL_PASSWORD: anitya
      POSTGRESQL_DATABASE: anitya
      POSTGRESQL_ADMIN_PASSWORD: anitya
    network_mode: bridge
    container_name: anitya-postgres
  anitya:
    image: slavek/anitya-server
    ports:
      - "31005:5000"
    links:
      - postgres
    network_mode: bridge
    container_name: anitya-server
    environment:
      ANITYA_POSTGRES_SERVICE_HOST: anitya-postgres
      ANITYA_POSTGRES_SERVICE_PORT: 5432
      POSTGRESQL_USER: anitya
      POSTGRESQL_PASSWORD: anitya
      POSTGRESQL_DATABASE: anitya
      POSTGRESQL_INITIAL_DATABASE: postgres
  update-job:
    image: slavek/anitya-server
    links:
      - postgres
    network_mode: bridge
    container_name: anitya-update-job
    entrypoint: /src/runupdatejob.sh
    environment:
      ANITYA_POSTGRES_SERVICE_HOST: anitya-postgres
      ANITYA_POSTGRES_SERVICE_PORT: 5432
      POSTGRESQL_USER: anitya
      POSTGRESQL_PASSWORD: anitya
      POSTGRESQL_DATABASE: anitya
