version: "2"
services:
  postgres:
    image: registry.centos.org/sclo/postgresql-95-centos7:latest
    environment:
      POSTGRESQL_USER: anitya
      POSTGRESQL_PASSWORD: anitya
      POSTGRESQL_DATABASE: anitya
      POSTGRESQL_ADMIN_PASSWORD: anitya
    network_mode: bridge
    container_name: anitya-postgres
  db-migrations:
    environment:
      ANITYA_POSTGRES_SERVICE_HOST: anitya-postgres
      ANITYA_POSTGRES_SERVICE_PORT: 5432
      POSTGRESQL_USER: anitya
      POSTGRESQL_PASSWORD: anitya
      POSTGRESQL_DATABASE: anitya
    image: slavek/anitya-db-migrations
    restart: on-failure
    network_mode: bridge
    container_name: anitya-db-migrations
    links:
      - postgres
  anitya:
    image: slavek/anitya-server
    ports:
      - "31005:5000"
    links:
      - postgres
    network_mode: bridge
    container_name: anitya-server
    environment:
      ANITYA_POSTGRES_SERVICE_HOST: anitya-postgres
      ANITYA_POSTGRES_SERVICE_PORT: 5432
      POSTGRESQL_USER: anitya
      POSTGRESQL_PASSWORD: anitya
      POSTGRESQL_DATABASE: anitya
  cron:
    image: slavek/anitya-cron
    links:
      - postgres
    network_mode: bridge
    container_name: anitya-cron
    environment:
      ANITYA_POSTGRES_SERVICE_HOST: anitya-postgres
      ANITYA_POSTGRES_SERVICE_PORT: 5432
      POSTGRESQL_USER: anitya
      POSTGRESQL_PASSWORD: anitya
      POSTGRESQL_DATABASE: anitya
